pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'your_credentials_id', url: 'https://github.com/your-repo.git']]])
            }
        }

        stage('Compile Code') {
            steps {
                sh './mvnw clean install -DskipTests'
            }

            post {
                success {
                    echo 'Compilation successful!'
                }
                failure {
                    echo 'Compilation failed!'
                    error('Compilation errors found. Exiting.')
                }
            }
        }

        stage('Deploy') {
            steps {
                sh './mvnw deploy'
            }
        }
    }
}
